//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class abrechnung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public abrechnung()
        {
            this.produktegruppe = new HashSet<produktegruppe>();
            this.softwaredienstleistung = new HashSet<softwaredienstleistung>();
        }
    
        public long abrechnung_id { get; set; }
        public long kundenkonto_fk { get; set; }
        public long location_fk { get; set; }
        public long device_fk { get; set; }
        public long interface_fk { get; set; }
    
        public virtual kundenkonto kundenkonto { get; set; }
        public virtual location location { get; set; }
        public virtual device device { get; set; }
        public virtual @interface @interface { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produktegruppe> produktegruppe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<softwaredienstleistung> softwaredienstleistung { get; set; }
    }
}
