//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class deviceport
    {
        public int deviceport_id { get; set; }
        public string description { get; set; }
        public long device_fk { get; set; }
        public long transportmedium_fk { get; set; }
    
        public virtual device device { get; set; }
        public virtual transportmedium transportmedium { get; set; }
    }
}
