//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class @interface
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public @interface()
        {
            this.abrechnung = new HashSet<abrechnung>();
        }
    
        public long interface_id { get; set; }
        public int network_fk { get; set; }
        public long device_fk { get; set; }
        public string ip_adress_v4 { get; set; }
        public string mac_adresse { get; set; }
        public byte[] isFullDuplex { get; set; }
        public Nullable<int> bandwith { get; set; }
        public Nullable<short> is_in_use { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<abrechnung> abrechnung { get; set; }
        public virtual device device { get; set; }
        public virtual network network { get; set; }
    }
}
