//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public long log_id { get; set; }
        public long device_fk { get; set; }
        public System.DateTime timestamp { get; set; }
        public string logMessage { get; set; }
        public string level { get; set; }
        public Nullable<short> is_acknowledged { get; set; }
    
        public virtual device device { get; set; }
    }
}
