//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class pointofdelivery
    {
        public long pod_id { get; set; }
        public long customer_id_fk { get; set; }
        public long contact_id_fk { get; set; }
        public long location_fk { get; set; }
        public string designation { get; set; }
        public System.TimeSpan timezone { get; set; }
        public short timeZonePositiv { get; set; }
        public string ntpServerIp { get; set; }
    
        public virtual contact contact { get; set; }
        public virtual customer customer { get; set; }
        public virtual location location { get; set; }
    }
}
