//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class produkte
    {
        public int artikelnummer_id { get; set; }
        public string artikelname { get; set; }
        public float preis { get; set; }
        public int produktegruppe_fk { get; set; }
    
        public virtual produktegruppe produktegruppe { get; set; }
    }
}
