//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class produktegruppe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produktegruppe()
        {
            this.produkte = new HashSet<produkte>();
        }
    
        public int produktegruppe_id { get; set; }
        public string hardware { get; set; }
        public string software { get; set; }
        public string sonstigeArtikel { get; set; }
        public long abrechung_fk { get; set; }
    
        public virtual abrechnung abrechnung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produkte> produkte { get; set; }
    }
}
