//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevicetypeHasOperatingsystem
    {
        public long DeviceType_fk { get; set; }
        public long Operatingsystem_fk { get; set; }
        public long Id { get; set; }
    
        public virtual Devicetype Devicetype { get; set; }
        public virtual Operatingsystem Operatingsystem { get; set; }
    }
}
