//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deviceport
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public long Device_fk { get; set; }
        public long Transportmedium_fk { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Transportmedium Transportmedium { get; set; }
    }
}
