//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interface
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Interface()
        {
            this.Accounting = new HashSet<Accounting>();
        }
    
        public long Id { get; set; }
        public int Network_fk { get; set; }
        public long Device_fk { get; set; }
        public string Ip_adress_v4 { get; set; }
        public string Mac_adresse { get; set; }
        public byte[] IsFullDuplex { get; set; }
        public Nullable<int> Bandwith { get; set; }
        public Nullable<short> Is_in_use { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounting> Accounting { get; set; }
        public virtual Device Device { get; set; }
        public virtual Network Network { get; set; }
    }
}
