//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long Id { get; set; }
        public long Device_fk { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string LogMessage { get; set; }
        public string Level { get; set; }
        public Nullable<short> Is_acknowledged { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
